// apps/web/src/app/register/page.tsx
'use client';

import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/lib/auth-context';
import Link from 'next/link';

export default function RegisterPage() {
  const searchParams = useSearchParams();
  const defaultRole = searchParams.get('role') as 'mentor' | 'mentee' | null;
  
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [fullName, setFullName] = useState('');
  const [role, setRole] = useState<'mentor' | 'mentee'>(defaultRole || 'mentee');
  const [isLoading, setIsLoading] = useState(false);
  const { register, error } = useAuth();
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      await register(email, password, fullName, role);
      router.push(role === 'mentor' ? '/mentor/profile' : '/mentors');
    } catch {
      // Error handled in context
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h1 className="text-center text-3xl font-bold text-gray-900">Mentory</h1>
          <h2 className="mt-2 text-center text-xl text-gray-600">Создать аккаунт</h2>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
              {error}
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label htmlFor="fullName" className="block text-sm font-medium text-gray-700">
                Имя и фамилия
              </label>
              <input
                id="fullName"
                type="text"
                required
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                placeholder="Иван Иванов"
              />
            </div>

            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                Email
              </label>
              <input
                id="email"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                placeholder="you@example.com"
              />
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                Пароль
              </label>
              <input
                id="password"
                type="password"
                required
                minLength={6}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                placeholder="Минимум 6 символов"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Я хочу:
              </label>
              <div className="grid grid-cols-2 gap-4">
                <button
                  type="button"
                  onClick={() => setRole('mentee')}
                  className={`p-4 border-2 rounded-lg text-center transition ${
                    role === 'mentee'
                      ? 'border-indigo-500 bg-indigo-50 text-indigo-700'
                      : 'border-gray-200 hover:border-gray-300'
                  }`}
                >
                  <div className="text-2xl mb-1">🎓</div>
                  <div className="font-medium">Найти ментора</div>
                  <div className="text-sm text-gray-500">Получить консультацию</div>
                </button>
                <button
                  type="button"
                  onClick={() => setRole('mentor')}
                  className={`p-4 border-2 rounded-lg text-center transition ${
                    role === 'mentor'
                      ? 'border-indigo-500 bg-indigo-50 text-indigo-700'
                      : 'border-gray-200 hover:border-gray-300'
                  }`}
                >
                  <div className="text-2xl mb-1">👨‍🏫</div>
                  <div className="font-medium">Стать ментором</div>
                  <div className="text-sm text-gray-500">Делиться опытом</div>
                </button>
              </div>
            </div>
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isLoading ? 'Регистрация...' : 'Зарегистрироваться'}
          </button>

          <p className="text-center text-sm text-gray-600">
            Уже есть аккаунт?{' '}
            <Link href="/login" className="font-medium text-indigo-600 hover:text-indigo-500">
              Войти
            </Link>
          </p>
        </form>
      </div>
    </div>
  );
}

// apps/web/src/routes/register/+page.svelte
<script lang="ts">
  import AppHeader from '$lib/components/AppHeader.svelte';
  import { register, error, isAuthenticated, isLoading } from '$lib/stores/auth';
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { superForm } from 'sveltekit-superforms/client';
  import { zodClient } from 'sveltekit-superforms/adapters';
  import { registerSchema, type RegisterForm } from '$lib/validators/auth';

  export let data;

  const form = superForm<RegisterForm>(data.form, {
    validators: zodClient(registerSchema as any),
    SPA: true,
    resetForm: false,
  });

  const { form: formData, errors } = form;
  const errorMessage = (err: unknown) => (Array.isArray(err) ? err[0] : err);
  let submitting = false;

  onMount(() => {
    const urlRole = $page.url.searchParams.get('role');
    if (urlRole === 'mentor' || urlRole === 'mentee') {
      formData.update((current) => ({ ...current, role: urlRole }));
    } else if (!$formData.role) {
      formData.update((current) => ({ ...current, role: 'mentee' }));
    }
    if ($isAuthenticated && !$isLoading) {
      goto('/mentors');
    }
  });

  const handleSubmit = async () => {
    const validation = await form.validateForm({ update: true });
    if (!validation.valid) {
      return;
    }
    submitting = true;
    try {
      const user = await register($formData.email, $formData.password, $formData.fullName, $formData.role);
      if (user.role === 'mentor' || user.role === 'both') {
        goto('/dashboard');
      } else {
        goto('/mentors');
      }
    } finally {
      submitting = false;
    }
  };
</script>

<div class="page">
  <AppHeader />

  <main class="container section" style="max-width:560px;">
    <div class="card">
      <h1 class="section-title">Создать аккаунт</h1>
      <p class="muted">Заполните основные данные.</p>

      {#if $error}
        <div class="surface" style="margin-top:12px;background:#fee2e2;border-color:#fecaca;color:#991b1b;">
          {$error}
        </div>
      {/if}

      <form class="stack" style="margin-top:18px;" on:submit|preventDefault={handleSubmit}>
        <label>
          <div class="muted" style="font-size:0.9rem;margin-bottom:6px;">Имя и фамилия</div>
          <input class="input" bind:value={$formData.fullName} placeholder="Иван Иванов" />
          {#if $errors.fullName}
            <div class="muted" style="font-size:0.8rem;color:#b45309;">{errorMessage($errors.fullName)}</div>
          {/if}
        </label>
        <label>
          <div class="muted" style="font-size:0.9rem;margin-bottom:6px;">Email</div>
          <input class="input" type="email" bind:value={$formData.email} placeholder="you@example.com" />
          {#if $errors.email}
            <div class="muted" style="font-size:0.8rem;color:#b45309;">{errorMessage($errors.email)}</div>
          {/if}
        </label>
        <label>
          <div class="muted" style="font-size:0.9rem;margin-bottom:6px;">Пароль</div>
          <input class="input" type="password" bind:value={$formData.password} placeholder="Минимум 8 символов" />
          {#if $errors.password}
            <div class="muted" style="font-size:0.8rem;color:#b45309;">{errorMessage($errors.password)}</div>
          {/if}
        </label>

        <div>
          <div class="muted" style="font-size:0.9rem;margin-bottom:10px;">Я хочу</div>
          <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;">
            <button type="button" class="card" style={`border:2px solid ${$formData.role === 'mentee' ? 'var(--accent)' : 'transparent'};`} on:click={() => formData.update((current) => ({ ...current, role: 'mentee' }))}>
              <strong>Найти ментора</strong>
              <p class="muted" style="margin-top:6px;">Получить консультацию</p>
            </button>
            <button type="button" class="card" style={`border:2px solid ${$formData.role === 'mentor' ? 'var(--accent)' : 'transparent'};`} on:click={() => formData.update((current) => ({ ...current, role: 'mentor' }))}>
              <strong>Стать ментором</strong>
              <p class="muted" style="margin-top:6px;">Делиться опытом</p>
            </button>
          </div>
        </div>

        <button class="btn btn-primary" type="submit" disabled={submitting}>
          {submitting ? 'Регистрация...' : 'Зарегистрироваться'}
        </button>
      </form>

      <p class="muted" style="margin-top:16px;">
        Уже есть аккаунт? <a href="/login" style="color:var(--accent);">Войти</a>
      </p>
    </div>
  </main>
</div>
