// apps/web/src/routes/mentors/[id]/+page.svelte
<script lang="ts">
  import AppHeader from '$lib/components/AppHeader.svelte';
  import Loading from '$lib/components/Loading.svelte';
  import { api, ApiError } from '$lib/api';
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { user } from '$lib/stores/auth';
  import { goto } from '$app/navigation';
  import { Star, Clock, Users, Globe, CheckCircle2, Calendar, ArrowLeft, MessageCircle, Video, ChevronRight } from 'lucide-svelte';

  interface MentorDetail {
    id: string;
    fullName: string;
    timezone: string;
    createdAt: string;
    mentorProfile: {
      headline: string;
      bio: string;
      education?: string | null;
      workplace?: string | null;
      goals?: string[];
      hobbies?: string[];
      languages: string[];
      ratingAvg: string;
      ratingCount: number;
      topics: { topic: { id: string; name: string } }[];
    };
    mentorServices: {
      id: string;
      title: string;
      durationMin: number;
      priceAmount: string;
      currency: string;
    }[];
    _count: { sessionsAsMentor: number };
  }

  interface Slot {
    id: string;
    startAt: string;
    endAt: string;
    status: string;
  }

  let mentor: MentorDetail | null = null;
  let slots: Slot[] = [];
  let selectedSlot: string | null = null;
  let selectedService: string | null = null;
  let isLoading = true;
  let isBooking = false;
  let error: string | null = null;

  const loadMentor = async (id: string) => {
    try {
      const mentorData = await api.get<MentorDetail>(`/mentors/${id}`);
      mentor = mentorData;
      selectedService = mentorData.mentorServices?.[0]?.id || null;

      try {
        const slotsResponse = await api.get<{ slots: Slot[] }>(`/scheduling/mentors/${id}/slots`);
        slots = (slotsResponse.slots || []).filter((s) => s.status === 'free');
      } catch {
        slots = [];
      }
    } catch {
      error = 'Не удалось загрузить профиль ментора';
    } finally {
      isLoading = false;
    }
  };

  onMount(() => {
    loadMentor($page.params.id);
  });

  const groupedSlots = () => {
    const map: Record<string, Slot[]> = {};
    slots.forEach((slot) => {
      const date = new Date(slot.startAt).toLocaleDateString('ru-RU', {
        weekday: 'long',
        day: 'numeric',
        month: 'long',
      });
      if (!map[date]) map[date] = [];
      map[date].push(slot);
    });
    return map;
  };

  const handleHold = async () => {
    if (!selectedSlot || !selectedService) return;

    if (!$user) {
      goto(`/login?redirect=/mentors/${$page.params.id}`);
      return;
    }

    isBooking = true;
    error = null;

    try {
      const result = await api.post<{ session: { id: string } }>('/booking/hold', {
        slotId: selectedSlot,
        serviceId: selectedService,
      });
      goto(`/checkout/${result.session.id}`);
    } catch (err) {
      if (err instanceof ApiError && err.status === 409) {
        error = 'Этот слот уже занят. Выберите другое время.';
      } else {
        error = 'Не удалось забронировать слот.';
      }
      selectedSlot = null;
      try {
        const slotsResponse = await api.get<{ slots: Slot[] }>(`/scheduling/mentors/${$page.params.id}/slots`);
        slots = (slotsResponse.slots || []).filter((s) => s.status === 'free');
      } catch {
        slots = [];
      }
    } finally {
      isBooking = false;
    }
  };

  $: selectedServiceData = mentor?.mentorServices?.find(s => s.id === selectedService);
</script>

<div class="page">
  <AppHeader />

  {#if isLoading}
    <Loading />
  {:else if error && !mentor}
    <main class="container section">
      <div class="error-state card">
        <h2>Ментор не найден</h2>
        <p class="muted">{error || 'Проверьте ссылку.'}</p>
        <a class="btn btn-outline" href="/mentors">
          <ArrowLeft size={16} /> Вернуться к каталогу
        </a>
      </div>
    </main>
  {:else if mentor}
    <main class="container section">
      <!-- Back link -->
      <a class="back-link" href="/mentors">
        <ArrowLeft size={16} /> Все менторы
      </a>

      <div class="mentor-layout">
        <!-- Main content -->
        <div class="mentor-main">
          <!-- Profile header -->
          <div class="profile-header card">
            <div class="profile-avatar">
              {mentor.fullName.charAt(0)}
            </div>
            <div class="profile-info">
              <h1 class="profile-name">{mentor.fullName}</h1>
              <p class="profile-headline">{mentor.mentorProfile?.headline || 'Эксперт'}</p>
              
              <div class="profile-stats">
                <div class="profile-stat">
                  <Star size={16} fill="currentColor" class="star-icon" />
                  <span class="stat-value">{mentor.mentorProfile?.ratingAvg || '0'}</span>
                  <span class="muted">({mentor.mentorProfile?.ratingCount || 0} отзывов)</span>
                </div>
                <div class="profile-stat">
                  <Users size={16} />
                  <span>{mentor._count?.sessionsAsMentor || 0} сессий</span>
                </div>
                {#if mentor.mentorProfile?.languages?.length}
                  <div class="profile-stat">
                    <Globe size={16} />
                    <span>{mentor.mentorProfile.languages.join(', ')}</span>
                  </div>
                {/if}
              </div>
            </div>
          </div>

          <!-- Bio -->
          <div class="card">
            <h2 class="card-title">
              <MessageCircle size={20} /> О менторе
            </h2>
            <p class="bio-text">{mentor.mentorProfile?.bio || 'Описание не указано.'}</p>
          </div>

          <div class="card">
            <h2 class="card-title">Профиль ментора</h2>
            <div class="stack" style="gap:10px;">
              <div>
                <div class="muted">Место работы</div>
                <div>{mentor.mentorProfile?.workplace || 'Не указано'}</div>
              </div>
              <div>
                <div class="muted">Образование</div>
                <div>{mentor.mentorProfile?.education || 'Не указано'}</div>
              </div>
              <div>
                <div class="muted">Хобби</div>
                <div>
                  {#if mentor.mentorProfile?.hobbies?.length}
                    {mentor.mentorProfile.hobbies.join(', ')}
                  {:else}
                    Не указано
                  {/if}
                </div>
              </div>
              <div>
                <div class="muted">Цели</div>
                <div>
                  {#if mentor.mentorProfile?.goals?.length}
                    {mentor.mentorProfile.goals.join(', ')}
                  {:else}
                    Не указано
                  {/if}
                </div>
              </div>
            </div>
          </div>

          <!-- Topics -->
          {#if mentor.mentorProfile?.topics?.length}
            <div class="card">
              <h2 class="card-title">
                <CheckCircle2 size={20} /> Экспертиза
              </h2>
              <div class="topics-grid">
                {#each mentor.mentorProfile.topics as topic}
                  <span class="topic-badge">
                    <CheckCircle2 size={14} /> {topic.topic.name}
                  </span>
                {/each}
              </div>
            </div>
          {/if}

          <!-- Services -->
          {#if mentor.mentorServices?.length}
            <div class="card">
              <h2 class="card-title">
                <Video size={20} /> Услуги
              </h2>
              <div class="services-list">
                {#each mentor.mentorServices as service}
                  <button
                    class="service-card {selectedService === service.id ? 'selected' : ''}"
                    on:click={() => (selectedService = service.id)}
                  >
                    <div class="service-info">
                      <div class="service-name">{service.title}</div>
                      <div class="service-duration">
                        <Clock size={14} /> {service.durationMin} минут
                      </div>
                    </div>
                    <div class="service-price">
                      {service.priceAmount} {service.currency}
                    </div>
                    {#if selectedService === service.id}
                      <div class="service-check">
                        <CheckCircle2 size={18} />
                      </div>
                    {/if}
                  </button>
                {/each}
              </div>
            </div>
          {/if}
        </div>

        <!-- Sidebar - Booking -->
        <aside class="booking-sidebar">
          <div class="booking-card card">
            <div class="booking-header">
              <Calendar size={20} />
              <h3>Забронировать сессию</h3>
            </div>

            {#if selectedServiceData}
              <div class="booking-service">
                <span>{selectedServiceData.title}</span>
                <span class="booking-price">{selectedServiceData.priceAmount} {selectedServiceData.currency}</span>
              </div>
            {/if}

            {#if error}
              <div class="alert alert-error">{error}</div>
            {/if}

            {#if Object.keys(groupedSlots()).length === 0}
              <div class="no-slots">
                <Calendar size={32} />
                <p>Нет доступных слотов</p>
                <span class="muted">Ментор пока не добавил расписание</span>
              </div>
            {:else}
              <div class="slots-container">
                {#each Object.entries(groupedSlots()) as [date, dateSlots]}
                  <div class="slots-day">
                    <div class="slots-date">{date}</div>
                    <div class="slots-grid">
                      {#each dateSlots as slot}
                        {@const time = new Date(slot.startAt).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })}
                        <button
                          class="slot-btn {selectedSlot === slot.id ? 'selected' : ''}"
                          on:click={() => (selectedSlot = slot.id)}
                        >
                          {time}
                        </button>
                      {/each}
                    </div>
                  </div>
                {/each}
              </div>
            {/if}

            <button 
              class="btn btn-primary btn-lg booking-btn" 
              on:click={handleHold} 
              disabled={!selectedSlot || isBooking || !selectedService}
            >
              {#if isBooking}
                Бронирование...
              {:else}
                Забронировать <ChevronRight size={18} />
              {/if}
            </button>

            <p class="booking-note muted">
              Слот удерживается на 10 минут для оплаты
            </p>
          </div>
        </aside>
      </div>
    </main>
  {/if}
</div>

<style>
  .back-link {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    color: var(--muted);
    font-size: 0.9rem;
    margin-bottom: 24px;
    transition: color 0.2s ease;
  }

  .back-link:hover {
    color: var(--ink);
  }

  .mentor-layout {
    display: grid;
    grid-template-columns: 1fr 380px;
    gap: 32px;
    align-items: start;
  }

  .mentor-main {
    display: flex;
    flex-direction: column;
    gap: 24px;
  }

  .profile-header {
    display: flex;
    gap: 24px;
    align-items: flex-start;
  }

  .profile-avatar {
    width: 100px;
    height: 100px;
    border-radius: 20px;
    background: linear-gradient(135deg, var(--accent) 0%, var(--violet) 100%);
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 700;
    font-size: 2.5rem;
    color: #fff;
    font-family: var(--font-display);
    flex-shrink: 0;
  }

  .profile-info {
    flex: 1;
  }

  .profile-name {
    font-size: 1.75rem;
    margin-bottom: 4px;
  }

  .profile-headline {
    color: var(--ink-secondary);
    font-size: 1.1rem;
    margin-bottom: 16px;
  }

  .profile-stats {
    display: flex;
    flex-wrap: wrap;
    gap: 16px;
  }

  .profile-stat {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 0.9rem;
    color: var(--ink-secondary);
  }

  .profile-stat :global(.star-icon) {
    color: #f59e0b;
  }

  .stat-value {
    font-weight: 600;
    color: var(--ink);
  }

  .card-title {
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 1.1rem;
    margin-bottom: 16px;
    color: var(--ink);
  }

  .card-title :global(svg) {
    color: var(--accent);
  }

  .bio-text {
    color: var(--ink-secondary);
    line-height: 1.7;
    white-space: pre-line;
  }

  .topics-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
  }

  .topic-badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 8px 14px;
    background: var(--accent-muted);
    color: var(--accent);
    border-radius: 999px;
    font-size: 0.875rem;
    font-weight: 500;
  }

  .services-list {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .service-card {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 16px 20px;
    background: var(--bg-alt);
    border: 2px solid transparent;
    border-radius: var(--radius-lg);
    cursor: pointer;
    transition: all 0.2s ease;
    text-align: left;
    width: 100%;
  }

  .service-card:hover {
    border-color: var(--border);
  }

  .service-card.selected {
    background: var(--accent-muted);
    border-color: var(--accent);
  }

  .service-info {
    flex: 1;
  }

  .service-name {
    font-weight: 600;
    margin-bottom: 4px;
  }

  .service-duration {
    display: flex;
    align-items: center;
    gap: 4px;
    color: var(--muted);
    font-size: 0.875rem;
  }

  .service-price {
    font-weight: 700;
    font-size: 1.1rem;
    color: var(--accent);
  }

  .service-check {
    color: var(--accent);
  }

  /* Booking sidebar */
  .booking-sidebar {
    position: sticky;
    top: 100px;
  }

  .booking-card {
    padding: 24px;
  }

  .booking-header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 20px;
  }

  .booking-header :global(svg) {
    color: var(--accent);
  }

  .booking-header h3 {
    margin: 0;
    font-size: 1.1rem;
  }

  .booking-service {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 16px;
    background: var(--bg-alt);
    border-radius: var(--radius-md);
    margin-bottom: 16px;
    font-size: 0.9rem;
  }

  .booking-price {
    font-weight: 700;
    color: var(--accent);
  }

  .no-slots {
    text-align: center;
    padding: 32px 16px;
    color: var(--muted);
  }

  .no-slots :global(svg) {
    margin-bottom: 12px;
    opacity: 0.5;
  }

  .no-slots p {
    font-weight: 600;
    color: var(--ink-secondary);
    margin-bottom: 4px;
  }

  .slots-container {
    max-height: 320px;
    overflow-y: auto;
    margin-bottom: 20px;
    padding-right: 8px;
  }

  .slots-day {
    margin-bottom: 16px;
  }

  .slots-day:last-child {
    margin-bottom: 0;
  }

  .slots-date {
    font-size: 0.8rem;
    font-weight: 600;
    text-transform: capitalize;
    color: var(--ink-secondary);
    margin-bottom: 8px;
  }

  .slots-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 8px;
  }

  .slot-btn {
    padding: 10px 8px;
    border: 1.5px solid var(--border);
    border-radius: var(--radius-md);
    background: var(--surface);
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--ink-secondary);
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .slot-btn:hover {
    border-color: var(--accent);
    color: var(--accent);
  }

  .slot-btn.selected {
    background: var(--accent);
    border-color: var(--accent);
    color: #fff;
  }

  .booking-btn {
    width: 100%;
    justify-content: center;
    margin-bottom: 12px;
  }

  .booking-note {
    text-align: center;
    font-size: 0.8rem;
  }

  .error-state {
    text-align: center;
    padding: 48px 24px;
  }

  .alert {
    margin-bottom: 16px;
  }

  @media (max-width: 900px) {
    .mentor-layout {
      grid-template-columns: 1fr;
    }

    .booking-sidebar {
      position: static;
    }

    .profile-header {
      flex-direction: column;
      align-items: center;
      text-align: center;
    }

    .profile-stats {
      justify-content: center;
    }
  }

  @media (max-width: 480px) {
    .profile-avatar {
      width: 80px;
      height: 80px;
      font-size: 2rem;
    }

    .slots-grid {
      grid-template-columns: repeat(2, 1fr);
    }
  }
</style>

// apps/web/src/app/mentors/[id]/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { api, ApiError } from '@/lib/api-client';
import { useAuth } from '@/lib/auth-context';

// API response type for single mentor
interface MentorDetail {
  id: string;
  fullName: string;
  timezone: string;
  createdAt: string;
  mentorProfile: {
    headline: string;
    bio: string;
    languages: string[];
    ratingAvg: string;
    ratingCount: number;
    topics: { topic: { id: string; name: string } }[];
  };
  mentorServices: {
    id: string;
    title: string;
    durationMin: number;
    priceAmount: string;
    currency: string;
  }[];
  _count: {
    sessionsAsMentor: number;
  };
}

interface Slot {
  id: string;
  startAt: string;
  endAt: string;
  status: string;
}

export default function MentorProfilePage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const { isAuthenticated } = useAuth();
  
  const [mentor, setMentor] = useState<MentorDetail | null>(null);
  const [slots, setSlots] = useState<Slot[]>([]);
  const [selectedSlot, setSelectedSlot] = useState<string | null>(null);
  const [selectedService, setSelectedService] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isBooking, setIsBooking] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Load mentor profile
  useEffect(() => {
    const loadData = async () => {
      try {
        const mentorData = await api.get<MentorDetail>(`/mentors/${id}`);
        setMentor(mentorData);
        
        // Set first service as default
        if (mentorData.mentorServices?.length > 0) {
          setSelectedService(mentorData.mentorServices[0].id);
        }
        
        // Try to load slots, but don't fail if endpoint doesn't exist
        try {
          const slotsResponse = await api.get<{ slots: Slot[] }>(`/scheduling/mentors/${id}/slots`);
          setSlots((slotsResponse.slots || []).filter(s => s.status === 'free'));
        } catch {
          // Slots endpoint might not be implemented yet
          setSlots([]);
        }
      } catch (err) {
        setError('Не удалось загрузить профиль ментора');
      } finally {
        setIsLoading(false);
      }
    };

    loadData();
  }, [id]);

  // Group slots by date
  const slotsByDate = slots.reduce((acc, slot) => {
    const date = new Date(slot.startAt).toLocaleDateString('ru-RU', {
      weekday: 'long',
      day: 'numeric',
      month: 'long'
    });
    if (!acc[date]) acc[date] = [];
    acc[date].push(slot);
    return acc;
  }, {} as Record<string, Slot[]>);

  const handleHoldSlot = async () => {
    if (!selectedSlot) return;
    
    if (!isAuthenticated) {
      router.push(`/login?redirect=/mentors/${id}`);
      return;
    }

    setIsBooking(true);
    setError(null);

    try {
      const result = await api.post<{ session: { id: string } }>('/booking/hold', {
        slotId: selectedSlot,
        serviceId: selectedService,
      });
      
      // Redirect to checkout
      router.push(`/checkout/${result.session.id}`);
    } catch (err) {
      if (err instanceof ApiError) {
        if (err.status === 409) {
          setError('Этот слот уже занят. Выберите другое время.');
          // Reload slots
          try {
            const slotsResponse = await api.get<{ slots: Slot[] }>(`/scheduling/mentors/${id}/slots`);
            setSlots((slotsResponse.slots || []).filter(s => s.status === 'free'));
          } catch {}
          setSelectedSlot(null);
        } else {
          setError('Не удалось забронировать слот');
        }
      }
    } finally {
      setIsBooking(false);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
      </div>
    );
  }

  if (!mentor) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Ментор не найден</h1>
          <Link href="/mentors" className="text-indigo-600 hover:underline">
            Вернуться к каталогу
          </Link>
        </div>
      </div>
    );
  }

  const profile = mentor.mentorProfile;
  const topics = profile?.topics?.map(t => t.topic) || [];
  const services = mentor.mentorServices || [];
  const minPrice = services.length > 0 
    ? Math.min(...services.map(s => parseFloat(s.priceAmount)))
    : null;

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
          <Link href="/mentors" className="text-indigo-600 hover:text-indigo-700">
            ← Назад к каталогу
          </Link>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Profile Info */}
          <div className="lg:col-span-2 space-y-6">
            {/* Header */}
            <div className="bg-white rounded-lg shadow p-6">
              <div className="flex items-start gap-6">
                <div className="w-24 h-24 bg-indigo-100 rounded-full flex items-center justify-center text-4xl shrink-0 text-indigo-600 font-bold">
                  {mentor.fullName?.charAt(0) || 'M'}
                </div>
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">{mentor.fullName}</h1>
                  <p className="text-gray-600">{profile?.headline}</p>
                  <div className="flex items-center gap-4 mt-2 flex-wrap">
                    <span className="text-yellow-500">⭐ {profile?.ratingAvg || '0'}</span>
                    <span className="text-gray-600">{profile?.ratingCount || 0} отзывов</span>
                    <span className="text-gray-600">{mentor._count?.sessionsAsMentor || 0} сессий</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Bio */}
            <div className="bg-white rounded-lg shadow p-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">О менторе</h2>
              <p className="text-gray-700 whitespace-pre-line">{profile?.bio || 'Описание не указано'}</p>
            </div>

            {/* Topics */}
            {topics.length > 0 && (
              <div className="bg-white rounded-lg shadow p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Темы</h2>
                <div className="flex flex-wrap gap-2">
                  {topics.map(topic => (
                    <span key={topic.id} className="px-3 py-1 bg-indigo-50 text-indigo-700 rounded-full">
                      {topic.name}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Services */}
            {services.length > 0 && (
              <div className="bg-white rounded-lg shadow p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Услуги</h2>
                <div className="space-y-3">
                  {services.map(service => (
                    <div 
                      key={service.id} 
                      className={`p-4 border rounded-lg cursor-pointer transition-colors ${
                        selectedService === service.id 
                          ? 'border-indigo-600 bg-indigo-50' 
                          : 'border-gray-200 hover:border-indigo-300'
                      }`}
                      onClick={() => setSelectedService(service.id)}
                    >
                      <div className="flex justify-between items-center">
                        <div>
                          <h3 className="font-medium text-gray-900">{service.title}</h3>
                          <p className="text-sm text-gray-600">{service.durationMin} минут</p>
                        </div>
                        <span className="text-lg font-bold text-indigo-600">
                          ${service.priceAmount} {service.currency}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Booking Sidebar */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-lg shadow p-6 sticky top-4">
              {minPrice !== null && (
                <div className="text-center mb-6">
                  <span className="text-sm text-gray-600">от</span>
                  <span className="text-3xl font-bold text-indigo-600 ml-1">${minPrice}</span>
                </div>
              )}

              {error && (
                <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded mb-4 text-sm">
                  {error}
                </div>
              )}

              <h3 className="font-semibold text-gray-900 mb-4">Доступные слоты</h3>

              {Object.keys(slotsByDate).length === 0 ? (
                <div className="text-center py-4">
                  <p className="text-gray-600 mb-4">Нет доступных слотов</p>
                  <p className="text-sm text-gray-500">
                    Ментор пока не добавил расписание
                  </p>
                </div>
              ) : (
                <div className="space-y-4 max-h-96 overflow-y-auto">
                  {Object.entries(slotsByDate).map(([date, dateSlots]) => (
                    <div key={date}>
                      <p className="text-sm font-medium text-gray-700 mb-2 capitalize">{date}</p>
                      <div className="grid grid-cols-2 gap-2">
                        {dateSlots.map(slot => {
                          const time = new Date(slot.startAt).toLocaleTimeString('ru-RU', {
                            hour: '2-digit',
                            minute: '2-digit'
                          });
                          const isSelected = selectedSlot === slot.id;
                          
                          return (
                            <button
                              key={slot.id}
                              onClick={() => setSelectedSlot(slot.id)}
                              className={`px-3 py-2 text-sm rounded border transition-colors ${
                                isSelected
                                  ? 'bg-indigo-600 text-white border-indigo-600'
                                  : 'border-gray-300 hover:border-indigo-600 hover:text-indigo-600'
                              }`}
                            >
                              {time}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  ))}
                </div>
              )}

              <button
                onClick={handleHoldSlot}
                disabled={!selectedSlot || isBooking || !selectedService}
                className="mt-6 w-full py-3 px-4 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isBooking ? 'Бронирование...' : 'Забронировать'}
              </button>

              <p className="mt-2 text-xs text-gray-500 text-center">
                Слот будет удержан на 10 минут для оплаты
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
